using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CmdPal.Ext.Spotify.Helpers
{
    public static class SpotifyMarkets
    {
        private static readonly Dictionary<string, string> native = new Dictionary<string, string>
        {
            { "AD", "Andorra" },
            { "AE", "الإمارات العربية المتحدة" },
            { "AG", "Antigua & Barbuda" },
            { "AL", "Shqipëri" },
            { "AM", "Հայաստան" },
            { "AO", "Angola" },
            { "AR", "Argentina" },
            { "AT", "Österreich" },
            { "AU", "Australia" },
            { "AZ", "Azərbaycan" },
            { "BA", "Bosna i Hercegovina" },
            { "BB", "Barbados" },
            { "BD", "বাংলাদেশ" },
            { "BE", "België" },
            { "BF", "Burkina Faso" },
            { "BG", "България" },
            { "BH", "البحرين" },
            { "BI", "Burundi" },
            { "BJ", "Bénin" },
            { "BN", "Brunei" },
            { "BO", "Bolivia" },
            { "BR", "Brasil" },
            { "BS", "Bahamas" },
            { "BW", "Botswana" },
            { "BY", "Беларусь" },
            { "BZ", "Belize" },
            { "CA", "Canada" },
            { "CD", "République démocratique du Congo" },
            { "CH", "Schweiz" },
            { "CI", "Côte d’Ivoire" },
            { "CL", "Chile" },
            { "CM", "Cameroun" },
            { "CO", "Colombia" },
            { "CR", "Costa Rica" },
            { "CV", "Cabo Verde" },
            { "CY", "Κύπρος" },
            { "CZ", "Česko" },
            { "DE", "Deutschland" },
            { "DJ", "Djibouti" },
            { "DK", "Danmark" },
            { "DM", "Dominica" },
            { "DO", "República Dominicana" },
            { "DZ", "الجزائر" },
            { "EC", "Ecuador" },
            { "EE", "Eesti" },
            { "EG", "مصر" },
            { "ES", "España" },
            { "ET", "ኢትዮጵያ" },
            { "FI", "Suomi" },
            { "FJ", "Fiji" },
            { "FR", "France" },
            { "GA", "Gabon" },
            { "GB", "United Kingdom" },
            { "GD", "Grenada" },
            { "GE", "საქართველო" },
            { "GH", "Ghana" },
            { "GM", "Gambia" },
            { "GR", "Ελλάδα" },
            { "GT", "Guatemala" },
            { "GW", "Guiné-Bissau" },
            { "GY", "Guyana" },
            { "HK", "香港" },
            { "HN", "Honduras" },
            { "HR", "Hrvatska" },
            { "HT", "Haïti" },
            { "HU", "Magyarország" },
            { "ID", "Indonesia" },
            { "IE", "Ireland" },
            { "IL", "ישראל" },
            { "IN", "भारत" },
            { "IQ", "العراق" },
            { "IS", "Ísland" },
            { "IT", "Italia" },
            { "JM", "Jamaica" },
            { "JO", "الأردن" },
            { "JP", "日本" },
            { "KE", "Kenya" },
            { "KG", "Кыргызстан" },
            { "KH", "កម្ពុជា" },
            { "KI", "Kiribati" },
            { "KM", "جزر القمر" },
            { "KN", "St. Kitts & Nevis" },
            { "KR", "대한민국" },
            { "KW", "الكويت" },
            { "KZ", "Қазақстан" },
            { "LA", "ລາວ" },
            { "LB", "لبنان" },
            { "LC", "St. Lucia" },
            { "LI", "Liechtenstein" },
            { "LK", "ශ්‍රී ලංකාව" },
            { "LR", "Liberia" },
            { "LS", "Lesotho" },
            { "LT", "Lietuva" },
            { "LU", "Lëtzebuerg" },
            { "LV", "Latvija" },
            { "LY", "ليبيا" },
            { "MA", "المغرب" },
            { "MC", "Monaco" },
            { "MD", "Republica Moldova" },
            { "ME", "Црна Гора" },
            { "MG", "Madagasikara" },
            { "MK", "Македонија" },
            { "ML", "Mali" },
            { "MN", "Монгол" },
            { "MO", "澳門" },
            { "MR", "موريتانيا" },
            { "MT", "Malta" },
            { "MU", "Mauritius" },
            { "MV", "Maldives" },
            { "MW", "Malawi" },
            { "MX", "México" },
            { "MY", "Malaysia" },
            { "MZ", "Moçambique" },
            { "NA", "Namibia" },
            { "NE", "Niger" },
            { "NG", "Nigeria" },
            { "NI", "Nicaragua" },
            { "NL", "Nederland" },
            { "NO", "Norge" },
            { "NP", "नेपाल" },
            { "NR", "Nauru" },
            { "NZ", "New Zealand" },
            { "OM", "عمان" },
            { "PA", "Panamá" },
            { "PE", "Perú" },
            { "PG", "Papua New Guinea" },
            { "PH", "Pilipinas" },
            { "PK", "پاکستان" },
            { "PL", "Polska" },
            { "PS", "السلطة الفلسطينية" },
            { "PT", "Portugal" },
            { "PW", "Palau" },
            { "PY", "Paraguay" },
            { "QA", "قطر" },
            { "RO", "România" },
            { "RS", "Србија" },
            { "RU", "Россия" },
            { "RW", "Rwanda" },
            { "SA", "المملكة العربية السعودية" },
            { "SB", "Solomon Islands" },
            { "SC", "Seychelles" },
            { "SE", "Sverige" },
            { "SG", "Singapore" },
            { "SI", "Slovenija" },
            { "SK", "Slovensko" },
            { "SL", "Sierra Leone" },
            { "SM", "San Marino" },
            { "SN", "Sénégal" },
            { "SR", "Suriname" },
            { "ST", "São Tomé e Príncipe" },
            { "SV", "El Salvador" },
            { "SZ", "Eswatini" },
            { "TD", "تشاد" },
            { "TG", "Togo" },
            { "TH", "ไทย" },
            { "TJ", "Тоҷикистон" },
            { "TL", "Timor-Leste" },
            { "TO", "Tonga" },
            { "TR", "Türkiye" },
            { "TT", "Trinidad & Tobago" },
            { "TW", "台灣" },
            { "TZ", "Tanzania" },
            { "UA", "Україна" },
            { "UG", "Uganda" },
            { "US", "United States" },
            { "UY", "Uruguay" },
            { "UZ", "Ўзбекистон" },
            { "VC", "St. Vincent & Grenadines" },
            { "VE", "Venezuela" },
            { "VN", "Việt Nam" },
            { "VU", "Vanuatu" },
            { "WS", "Samoa" },
            { "XK", "Kosovë" },
            { "ZA", "Suid-Afrika" },
            { "ZM", "Zambia" },
            { "ZW", "Zimbabwe" }
        };

        /// <summary>
        /// A read-only collection of all Spotify market codes and their native country names.
        /// </summary>
        public static IReadOnlyDictionary<string, string> Native => new ReadOnlyDictionary<string, string>(native);
    }
}

